'use client';

import React, { createContext, useState, useContext, useEffect } from 'react';

const LanguageContext = createContext();

const translations = {
  'English': {
    'Sign in': 'Sign in',
    'Email address': 'Email address',
    'Enter password': 'Enter password',
    'Log in': 'Log in',
    'Forget password?': 'Forget password?',
    'Signing in...': 'Signing in...',
    'or continue with': 'or continue with',
    'Google': 'Google',
    'Apple': 'Apple',
    'Don\'t have an account?': 'Don\'t have an account?',
    'Sign Up': 'Sign Up',
    'Select Language': 'Select Language',
    'Home Dashboard': 'Home Dashboard',
    'Patient Profile': 'Patient Profile',
    'Daily Check-in': 'Daily Check-in',
    'Schedule': 'Schedule',
    'AI Guide': 'AI Guide',
    'Medicine': 'Medicine',
    'Diseases': 'Diseases',
    'Diets': 'Diets',
    'Exercises': 'Exercises',
    'Yoga': 'Yoga',
    'Disease Scan': 'Disease Scan',
    'Health Records': 'Health Records',
    'Cloud Health Sync': 'Cloud Health Sync',
    'Connected to Google Fit as': 'Connected to Google Fit as',
    'Not connected to any cloud service': 'Not connected to any cloud service',
    'Connect Google Fit': 'Connect Google Fit',
    'Fetch Latest Data': 'Fetch Latest Data',
    'Syncing...': 'Syncing...',
    'Collapse': 'Collapse',
    'See All': 'See All',
    'Steps': 'Steps',
    'Live HR': 'Live HR',
    'Heart Rate': 'Heart Rate',
    'Live': 'Live',
    'Connect watch for live data': 'Connect watch for live data',
    'Sleep': 'Sleep',
    'Score': 'Score',
    'Calories': 'Calories',
    'active': 'active',
    'Medicine Database': 'Medicine Database',
    'Search medicines...': 'Search medicines...',
    'Usage': 'Usage',
    'Dosage': 'Dosage',
    'Side Effects': 'Side Effects',
    'Warning': 'Warning',
    'No medicines found': 'No medicines found',
    'No results matching': 'No results matching',
    'All': 'All',
    'Painkillers': 'Painkillers',
    'Antibiotics': 'Antibiotics',
    'Diabetes': 'Diabetes',
    'Heart': 'Heart',
    'My Streak': 'My Streak',
    'Days in a row!': 'Days in a row!',
    'Check-in Today': 'Check-in Today',
    'Sun': 'Sun', 'Mon': 'Mon', 'Tue': 'Tue', 'Wed': 'Wed', 'Thu': 'Thu', 'Fri': 'Fri', 'Sat': 'Sat'
  },
  'हिंदी': {
    'Sign in': 'साइन इन करें',
    'Email address': 'ईमेल पता',
    'Enter password': 'अपना पासवर्ड दर्ज करें',
    'Log in': 'लॉग इन करें',
    'Forget password?': 'पासवर्ड भूल गए?',
    'Signing in...': 'साइन इन हो रहा है...',
    'or continue with': 'या इसके साथ जारी रखें',
    'Google': 'गूगल',
    'Apple': 'एप्पल',
    'Don\'t have an account?': 'क्या आपके पास खाता नहीं है?',
    'Sign Up': 'साइन अप करें',
    'Select Language': 'भाषा चुनें',
    'Home Dashboard': 'होम डैशबोर्ड',
    'Patient Profile': 'मरीज की प्रोफ़ाइल',
    'Daily Check-in': 'दैनिक चेक-इन',
    'Schedule': 'अनुसूची',
    'AI Guide': 'एआई गाइड',
    'Medicine': 'दवा',
    'Diseases': 'बीमारियां',
    'Diets': 'आहार',
    'Exercises': 'व्यायाम',
    'Yoga': 'योग',
    'Disease Scan': 'रोग स्कैन',
    'Health Records': 'स्वास्थ्य रिकॉर्ड',
    'Cloud Health Sync': 'क्लाउड स्वास्थ्य सिंक',
    'Connected to Google Fit as': 'Google Fit से जुड़े हैं:',
    'Not connected to any cloud service': 'किसी क्लाउड सेवा से नहीं जुड़े',
    'Connect Google Fit': 'Google Fit से जुड़ें',
    'Fetch Latest Data': 'नवीनतम डेटा प्राप्त करें',
    'Syncing...': 'सिंक हो रहा है...',
    'Collapse': 'संक्षिप्त करें',
    'See All': 'सभी देखें',
    'Steps': 'कदम',
    'Live HR': 'लाइव हृदय गति',
    'Heart Rate': 'हृदय गति',
    'Live': 'लाइव',
    'Connect watch for live data': 'लाइव डेटा के लिए वॉच कनेक्ट करें',
    'Sleep': 'नींद',
    'Score': 'स्कोर',
    'Calories': 'कैलोरी',
    'active': 'सक्रिय',
    'Medicine Database': 'दवा डेटाबेस',
    'Search medicines...': 'दवाएं खोजें...',
    'Usage': 'उपयोग',
    'Dosage': 'खुराक',
    'Side Effects': 'दुष्प्रभाव',
    'Warning': 'चेतावनी',
    'No medicines found': 'कोई दवा नहीं मिली',
    'No results matching': 'से मेल खाने वाले कोई परिणाम नहीं',
    'All': 'सभी',
    'Painkillers': 'दर्द निवारक',
    'Antibiotics': 'एंटीबायोटिक्स',
    'Diabetes': 'मधुमेह',
    'Heart': 'हृदय',
    'My Streak': 'मेरी स्ट्रीक',
    'Days in a row!': 'लगातार दिन!',
    'Check-in Today': 'आज चेक-इन करें',
    'Sun': 'रवि', 'Mon': 'सोम', 'Tue': 'मंगल', 'Wed': 'बुध', 'Thu': 'गुरु', 'Fri': 'शुक्र', 'Sat': 'शनि'
  },
  'తెలుగు': {
    'Sign in': 'సైన్ ఇన్ చేయండి',
    'Email address': 'ఇమెయిల్ చిరునామా',
    'Enter password': 'మీ పాస్‌వర్డ్‌ను నమోదు చేయండి',
    'Log in': 'లాగిన్ చేయండి',
    'Forget password?': 'పాస్‌వర్డ్ మర్చిపోయారా?',
    'Signing in...': 'సైన్ ఇన్ అవుతోంది...',
    'or continue with': 'లేదా దీనితో కొనసాగించండి',
    'Google': 'గూగుల్',
    'Apple': 'ఆపిల్',
    'Don\'t have an account?': 'ఖాతా లేదా?',
    'Sign Up': 'సైన్ అప్ చేయండి',
    'Select Language': 'భాషను ఎంచుకోండి',
    'Home Dashboard': 'హోమ్ డాష్‌బోర్డ్',
    'Patient Profile': 'రోగి ప్రొఫైల్',
    'Daily Check-in': 'రోజువారీ చెక్-ఇన్',
    'Schedule': 'షెడ్యూల్',
    'AI Guide': 'AI గైడ్',
    'Medicine': 'ఔషధం',
    'Diseases': 'వ్యాధులు',
    'Diets': 'ఆహారాలు',
    'Exercises': 'వ్యాయామాలు',
    'Yoga': 'యోగా',
    'Disease Scan': 'వ్యాధి స్కాన్',
    'Health Records': 'ఆరోగ్య రికార్డులు',
    'Cloud Health Sync': 'క్లౌడ్ హెల్త్ సింక్',
    'Connected to Google Fit as': 'Google Fitకి కనెక్ట్ చేయబడింది:',
    'Not connected to any cloud service': 'ఏ క్లౌడ్ సేవకు కనెక్ట్ కాలేదు',
    'Connect Google Fit': 'Google Fit కనెక్ట్ చేయండి',
    'Fetch Latest Data': 'తాజా డేటాను పొందండి',
    'Syncing...': 'సింక్ అవుతోంది...',
    'Collapse': 'కుదించు',
    'See All': 'అన్ని చూడండి',
    'Steps': 'అడుగులు',
    'Live HR': 'లైవ్ HR',
    'Heart Rate': 'హృదయ స్పందన రేటు',
    'Live': 'లైవ్',
    'Connect watch for live data': 'లైవ్ డేటా కోసం వాచ్ కనెక్ట్ చేయండి',
    'Sleep': 'నిద్ర',
    'Score': 'స్కోర్',
    'Calories': 'కేలరీలు',
    'active': 'చురుకైన',
    'Medicine Database': 'మెడిసిన్ డేటాబేస్',
    'Search medicines...': 'మందులను శోధించండి...',
    'Usage': 'వాడుక',
    'Dosage': 'మోతాదు',
    'Side Effects': 'దుష్ప్రభావాలు',
    'Warning': 'హెచ్చరిక',
    'No medicines found': 'మందులు దొరకలేదు',
    'No results matching': 'సరిపోలే ఫలితాలు లేవు',
    'All': 'అన్ని',
    'Painkillers': 'నొప్పి నివారణలు',
    'Antibiotics': 'యాంటీబయాటిక్స్',
    'Diabetes': 'మధుమేహం',
    'Heart': 'గుండె',
    'My Streak': 'నా స్ట్రీక్',
    'Days in a row!': 'వరుసగా రోజులు!',
    'Check-in Today': 'ఈ రోజు చెక్-ఇన్',
    'Sun': 'ఆది', 'Mon': 'సోమ', 'Tue': 'మంగళ', 'Wed': 'బుధ', 'Thu': 'గురు', 'Fri': 'శుక్ర', 'Sat': 'శని'
  },
  'தமிழ்': {
    'Sign in': 'உள்நுழைக',
    'Email address': 'மின்னஞ்சல் முகவரி',
    'Enter password': 'உங்கள் கடவுச்சொல்லை உள்ளிடவும்',
    'Log in': 'உள்நுழையவும்',
    'Forget password?': 'கடவுச்சொல்லை மறந்துவிட்டீர்களா?',
    'Signing in...': 'உள்நுழைகிறது...',
    'or continue with': 'அல்லது இதனுடன் தொடரவும்',
    'Google': 'கூகிள்',
    'Apple': 'ஆப்பிள்',
    'Don\'t have an account?': 'கணக்கு இல்லையா?',
    'Sign Up': 'பதிவு செய்க',
    'Select Language': 'மொழியைத் தேர்ந்தெடுக்கவும்',
    'Home Dashboard': 'முகப்பு டாஷ்போர்டு',
    'Patient Profile': 'நோயாளி சுயவிவரம்',
    'Daily Check-in': 'தினசரி செக்-இன்',
    'Schedule': 'அட்டவணை',
    'AI Guide': 'AI வழிகாட்டி',
    'Medicine': 'மருந்து',
    'Diseases': 'நோய்கள்',
    'Diets': 'உணவுகள்',
    'Exercises': 'பயிற்சிகள்',
    'Yoga': 'யோகா',
    'Disease Scan': 'நோய் ஸ்கேன்',
    'Health Records': 'சுகாதார பதிவுகள்',
    'Cloud Health Sync': 'கிளவுட் ஹெல்த் சின்க்',
    'Connected to Google Fit as': 'Google Fit உடன் இணைக்கப்பட்டுள்ளது:',
    'Not connected to any cloud service': 'எந்த கிளவுட் சேவையுடனும் இணைக்கப்படவில்லை',
    'Connect Google Fit': 'Google Fit இணைக்கவும்',
    'Fetch Latest Data': 'சமீபத்திய தரவைப் பெறவும்',
    'Syncing...': 'ஒத்திசைகிறது...',
    'Collapse': 'சுருக்கு',
    'See All': 'அனைத்தையும் காண்',
    'Steps': 'படிகள்',
    'Live HR': 'நேரடி இதயம்',
    'Heart Rate': 'இதய துடிப்பு',
    'Live': 'நேரடி',
    'Connect watch for live data': 'தரவுக்கு வாட்சை இணைக்கவும்',
    'Sleep': 'தூக்கம்',
    'Score': 'மதிப்பெண்',
    'Calories': 'கலோரிகள்',
    'active': 'செயலில்',
    'Medicine Database': 'மருந்து தரவுத்தளம்',
    'Search medicines...': 'மருந்துகளைத் தேடுங்கள்...',
    'Usage': 'பயன்பாடு',
    'Dosage': 'மருந்தளவு',
    'Side Effects': 'பக்க விளைவுகள்',
    'Warning': 'எச்சரிக்கை',
    'No medicines found': 'மருந்துகள் இல்லை',
    'No results matching': 'முடிவுகள் இல்லை',
    'All': 'அனைத்தும்',
    'Painkillers': 'வலி நிவாரணிகள்',
    'Antibiotics': 'நுண்ணுயிர் எதிர்ப்பிகள்',
    'Diabetes': 'நீரிழிவு',
    'Heart': 'இதயம்',
    'My Streak': 'எனது ஸ்ட்ரீக்',
    'Days in a row!': 'தொடர்ச்சியாக நாட்கள்!',
    'Check-in Today': 'இன்று செக்-இன்',
    'Sun': 'ஞா', 'Mon': 'தி', 'Tue': 'செ', 'Wed': 'பு', 'Thu': 'வி', 'Fri': 'வெ', 'Sat': 'ச'
  },
  'मराठी': {
    'Sign in': 'साइन इन करा',
    'Email address': 'ईमेल पत्ता',
    'Enter password': 'तुमचा पासवर्ड प्रविष्ट करा',
    'Log in': 'लॉग इन करा',
    'Forget password?': 'पासवर्ड विसरलात?',
    'Signing in...': 'साइन इन होत आहे...',
    'or continue with': 'किंवा याद्वारे सुरू ठेवा',
    'Google': 'गुगल',
    'Apple': 'ऍपल',
    'Don\'t have an account?': 'खाते नाही?',
    'Sign Up': 'साइन अप करा',
    'Select Language': 'भाषा निवडा',
    'Home Dashboard': 'होम डॅशबोर्ड',
    'Patient Profile': 'रुग्ण प्रोफाइल',
    'Daily Check-in': 'दैनिक चेक-इन',
    'Schedule': 'वेळापत्रक',
    'AI Guide': 'AI मार्गदर्शक',
    'Medicine': 'औषध',
    'Diseases': 'आजार',
    'Diets': 'आहार',
    'Exercises': 'व्यायाम',
    'Yoga': 'योग',
    'Disease Scan': 'रोग स्कॅन',
    'Health Records': 'आरोग्य नोंदी',
    'Cloud Health Sync': 'क्लाउड आरोग्य सिंक',
    'Connected to Google Fit as': 'Google Fit शी कनेक्ट केले आहे:',
    'Not connected to any cloud service': 'कोणत्याही क्लाउड सेवेशी कनेक्ट केलेले नाही',
    'Connect Google Fit': 'Google Fit कनेक्ट करा',
    'Fetch Latest Data': 'नवीनतम डेटा मिळवा',
    'Syncing...': 'सिंक करत आहे...',
    'Collapse': 'संकुचित करा',
    'See All': 'सर्व पहा',
    'Steps': 'पावले',
    'Live HR': 'थेट हृदय गती',
    'Heart Rate': 'हृदय गती',
    'Live': 'थेट',
    'Connect watch for live data': 'थेट डेटासाठी घड्याळ कनेक्ट करा',
    'Sleep': 'झोप',
    'Score': 'गुण',
    'Calories': 'कॅलरीज',
    'active': 'सक्रिय',
    'Medicine Database': 'औषध डेटाबेस',
    'Search medicines...': 'औषधे शोधा...',
    'Usage': 'वापर',
    'Dosage': 'डोस',
    'Side Effects': 'दुष्परिणाम',
    'Warning': 'चेतावणी',
    'No medicines found': 'कोणतीही औषधे आढळली नाहीत',
    'No results matching': 'कोणतेही परिणाम जुळत नाहीत',
    'All': 'सर्व',
    'Painkillers': 'पेनकिलर्स',
    'Antibiotics': 'अँटीबायोटिक्स',
    'Diabetes': 'मधुमेह',
    'Heart': 'हृदय',
    'My Streak': 'माझी स्ट्रीक',
    'Days in a row!': 'सलग दिवस!',
    'Check-in Today': 'आज चेक-इन',
    'Sun': 'रवी', 'Mon': 'सोम', 'Tue': 'मंगळ', 'Wed': 'बुध', 'Thu': 'गुरु', 'Fri': 'शुक्र', 'Sat': 'शनी'
  },
  'ગુજરાતી': {
    'Sign in': 'સાઇન ઇન કરો',
    'Email address': 'ઇમેઇલ સરનામું',
    'Enter password': 'તમારો પાસવર્ડ દાખલ કરો',
    'Log in': 'લૉગ ઇન કરો',
    'Forget password?': 'પાસવર્ડ ભૂલી ગયા છો?',
    'Signing in...': 'સાઇન ઇન થઈ રહ્યું છે...',
    'or continue with': 'અથવા આની સાથે ચાલુ રાખો',
    'Google': 'ગૂગલ',
    'Apple': 'એપલ',
    'Don\'t have an account?': 'શું તમારી પાસે ખાતું નથી?',
    'Sign Up': 'સાઇન અપ કરો',
    'Select Language': 'ભાષા પસંદ કરો',
    'Home Dashboard': 'હોમ ડેશબોર્ડ',
    'Patient Profile': 'દર્દી પ્રોફાઇલ',
    'Daily Check-in': 'દૈનિક ચેક-ઇન',
    'Schedule': 'શેડ્યૂલ',
    'AI Guide': 'AI માર્ગદર્શિકા',
    'Medicine': 'દવા',
    'Diseases': 'રોગો',
    'Diets': 'આહાર',
    'Exercises': 'કસરતો',
    'Yoga': 'યોગ',
    'Disease Scan': 'રોગ સ્કેન',
    'Health Records': 'આરોગ્ય રેકોર્ડ્સ',
    'Cloud Health Sync': 'ક્લાઉડ હેલ્થ સિંક',
    'Connected to Google Fit as': 'Google Fit સાથે જોડાયેલ:',
    'Not connected to any cloud service': 'કોઈ ક્લાઉડ સેવા સાથે જોડાયેલ નથી',
    'Connect Google Fit': 'Google Fit જોડો',
    'Fetch Latest Data': 'નવીનતમ ડેટા લાવો',
    'Syncing...': 'સિંક થઈ રહ્યું છે...',
    'Collapse': 'સંકેલો',
    'See All': 'બધું જુઓ',
    'Steps': 'પગલાં',
    'Live HR': 'લાઇવ હાર્ટ રેટ',
    'Heart Rate': 'હાર્ટ રેટ',
    'Live': 'લાઇવ',
    'Connect watch for live data': 'લાઇવ ડેટા માટે ઘડિયાળ જોડો',
    'Sleep': 'ઊંઘ',
    'Score': 'સ્કોર',
    'Calories': 'કેલરી',
    'active': 'સક્રિય',
    'Medicine Database': 'દવા ડેટાબેઝ',
    'Search medicines...': 'દવાઓ શોધો...',
    'Usage': 'ઉપયોગ',
    'Dosage': 'ડોઝ',
    'Side Effects': 'આડઅસરો',
    'Warning': 'ચેતવણી',
    'No medicines found': 'કોઈ દવા મળી નથી',
    'No results matching': 'કોઈ પરિણામ મેળ ખાતું નથી',
    'All': 'બધા',
    'Painkillers': 'પેઇનકિલર્સ',
    'Antibiotics': 'એન્ટિબાયોટિક્સ',
    'Diabetes': 'ડાયાબિટીસ',
    'Heart': 'હૃદય',
    'My Streak': 'મારી સ્ટ્રીક',
    'Days in a row!': 'સળંગ દિવસો!',
    'Check-in Today': 'આજે ચેક-ઇન',
    'Sun': 'રવિ', 'Mon': 'સોમ', 'Tue': 'મંગળ', 'Wed': 'બુધ', 'Thu': 'ગુરુ', 'Fri': 'શુક્ર', 'Sat': 'શનિ'
  }
};

export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState('English');

  // Load saved language on mount
  useEffect(() => {
    const saved = localStorage.getItem('fitmadix_lang');
    if (saved && translations[saved]) {
      // eslint-disable-next-line
      setLanguage(saved);
    }
  }, []);

  const changeLanguage = (lang) => {
    if (translations[lang]) {
      setLanguage(lang);
      localStorage.setItem('fitmadix_lang', lang);
    }
  };

  const t = (key) => {
    if (!translations[language]) return key;
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, changeLanguage, t, supportedLanguages: Object.keys(translations) }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  return useContext(LanguageContext);
}
