/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as EncyclopediaRouteRouteImport } from './routes/encyclopedia/route'
import { Route as FoodRouteImport } from './routes/food'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as ProductsRouteRouteImport } from './routes/products/route'
import { Route as AuthenticatedAccessibilityRouteImport } from './routes/_authenticated/accessibility'
import { Route as AuthenticatedAiCoachRouteImport } from './routes/_authenticated/ai-coach'
import { Route as AuthenticatedAnalyticsRouteImport } from './routes/_authenticated/analytics'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedExerciseRouteImport } from './routes/_authenticated/exercise'
import { Route as AuthenticatedExercisesRouteImport } from './routes/_authenticated/exercises'
import { Route as AuthenticatedFoodLogRouteImport } from './routes/_authenticated/food-log'
import { Route as AuthenticatedFoodScanRouteImport } from './routes/_authenticated/food-scan'
import { Route as AuthenticatedHubRouteImport } from './routes/_authenticated/hub'
import { Route as AuthenticatedMedicinesRouteImport } from './routes/_authenticated/medicines'
import { Route as AuthenticatedNearbyRouteImport } from './routes/_authenticated/nearby'
import { Route as AuthenticatedNutritionRouteImport } from './routes/_authenticated/nutrition'
import { Route as AuthenticatedPrescriptionRouteImport } from './routes/_authenticated/prescription'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as AuthenticatedReportsRouteImport } from './routes/_authenticated/reports'
import { Route as AuthenticatedSymptomsRouteImport } from './routes/_authenticated/symptoms'
import { Route as AuthenticatedTimelineRouteImport } from './routes/_authenticated/timeline'
import { Route as AuthenticatedVitalsRouteImport } from './routes/_authenticated/vitals'
import { Route as AuthenticatedWorkoutsRouteImport } from './routes/_authenticated/workouts'
import { Route as AdminEncyclopediaRouteImport } from './routes/admin/encyclopedia'
import { Route as EncyclopediaIndexRouteImport } from './routes/encyclopedia/index'
import { Route as EncyclopediaSearchRouteImport } from './routes/encyclopedia/search'
import { Route as ProductsIndexRouteImport } from './routes/products/index'
import { Route as ProductsSlugRouteImport } from './routes/products/$slug'
import { Route as ProductsCompareRouteImport } from './routes/products/compare'
import { Route as AuthenticatedChatIndexRouteImport } from './routes/_authenticated/chat.index'
import { Route as AuthenticatedChatThreadIdRouteImport } from './routes/_authenticated/chat.$threadId'
import { Route as AuthenticatedEncyclopediaDiseaseRouteImport } from './routes/_authenticated/encyclopedia.disease'
import { Route as AuthenticatedEncyclopediaFoodRouteImport } from './routes/_authenticated/encyclopedia.food'
import { Route as AuthenticatedEncyclopediaMedicineRouteImport } from './routes/_authenticated/encyclopedia.medicine'
import { Route as AuthenticatedExerciseWorkoutIdRouteImport } from './routes/_authenticated/exercise.$workoutId'
import { Route as AuthenticatedFoodLogSettingsRouteImport } from './routes/_authenticated/food-log.settings'
import { Route as EncyclopediaCategoryIndexRouteImport } from './routes/encyclopedia/$category/index'
import { Route as EncyclopediaCategorySlugRouteImport } from './routes/encyclopedia/$category/$slug'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const EncyclopediaRouteRoute = EncyclopediaRouteRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => rootRouteImport,
} as any)
const FoodRoute = FoodRouteImport.update({
  id: '/food',
  path: '/food',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsRouteRoute = ProductsRouteRouteImport.update({
  id: '/products',
  path: '/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAccessibilityRoute =
  AuthenticatedAccessibilityRouteImport.update({
    id: '/accessibility',
    path: '/accessibility',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAiCoachRoute = AuthenticatedAiCoachRouteImport.update({
  id: '/ai-coach',
  path: '/ai-coach',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAnalyticsRoute = AuthenticatedAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExerciseRoute = AuthenticatedExerciseRouteImport.update({
  id: '/exercise',
  path: '/exercise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExercisesRoute = AuthenticatedExercisesRouteImport.update({
  id: '/exercises',
  path: '/exercises',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodLogRoute = AuthenticatedFoodLogRouteImport.update({
  id: '/food-log',
  path: '/food-log',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFoodScanRoute = AuthenticatedFoodScanRouteImport.update({
  id: '/food-scan',
  path: '/food-scan',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHubRoute = AuthenticatedHubRouteImport.update({
  id: '/hub',
  path: '/hub',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMedicinesRoute = AuthenticatedMedicinesRouteImport.update({
  id: '/medicines',
  path: '/medicines',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNearbyRoute = AuthenticatedNearbyRouteImport.update({
  id: '/nearby',
  path: '/nearby',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedNutritionRoute = AuthenticatedNutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPrescriptionRoute =
  AuthenticatedPrescriptionRouteImport.update({
    id: '/prescription',
    path: '/prescription',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedReportsRoute = AuthenticatedReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSymptomsRoute = AuthenticatedSymptomsRouteImport.update({
  id: '/symptoms',
  path: '/symptoms',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTimelineRoute = AuthenticatedTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedVitalsRoute = AuthenticatedVitalsRouteImport.update({
  id: '/vitals',
  path: '/vitals',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedWorkoutsRoute = AuthenticatedWorkoutsRouteImport.update({
  id: '/workouts',
  path: '/workouts',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AdminEncyclopediaRoute = AdminEncyclopediaRouteImport.update({
  id: '/encyclopedia',
  path: '/encyclopedia',
  getParentRoute: () => AdminRouteRoute,
} as any)
const EncyclopediaIndexRoute = EncyclopediaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => EncyclopediaRouteRoute,
} as any)
const EncyclopediaSearchRoute = EncyclopediaSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => EncyclopediaRouteRoute,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsSlugRoute = ProductsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const ProductsCompareRoute = ProductsCompareRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => ProductsRouteRoute,
} as any)
const AuthenticatedChatIndexRoute = AuthenticatedChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedChatThreadIdRoute =
  AuthenticatedChatThreadIdRouteImport.update({
    id: '/chat/$threadId',
    path: '/chat/$threadId',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncyclopediaDiseaseRoute =
  AuthenticatedEncyclopediaDiseaseRouteImport.update({
    id: '/encyclopedia/disease',
    path: '/encyclopedia/disease',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncyclopediaFoodRoute =
  AuthenticatedEncyclopediaFoodRouteImport.update({
    id: '/encyclopedia/food',
    path: '/encyclopedia/food',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedEncyclopediaMedicineRoute =
  AuthenticatedEncyclopediaMedicineRouteImport.update({
    id: '/encyclopedia/medicine',
    path: '/encyclopedia/medicine',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedExerciseWorkoutIdRoute =
  AuthenticatedExerciseWorkoutIdRouteImport.update({
    id: '/$workoutId',
    path: '/$workoutId',
    getParentRoute: () => AuthenticatedExerciseRoute,
  } as any)
const AuthenticatedFoodLogSettingsRoute =
  AuthenticatedFoodLogSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedFoodLogRoute,
  } as any)
const EncyclopediaCategoryIndexRoute =
  EncyclopediaCategoryIndexRouteImport.update({
    id: '/$category/',
    path: '/$category/',
    getParentRoute: () => EncyclopediaRouteRoute,
  } as any)
const EncyclopediaCategorySlugRoute =
  EncyclopediaCategorySlugRouteImport.update({
    id: '/$category/$slug',
    path: '/$category/$slug',
    getParentRoute: () => EncyclopediaRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/encyclopedia': typeof EncyclopediaRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/food': typeof FoodRoute
  '/onboarding': typeof OnboardingRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercise': typeof AuthenticatedExerciseRouteWithChildren
  '/exercises': typeof AuthenticatedExercisesRoute
  '/food-log': typeof AuthenticatedFoodLogRouteWithChildren
  '/food-scan': typeof AuthenticatedFoodScanRoute
  '/hub': typeof AuthenticatedHubRoute
  '/medicines': typeof AuthenticatedMedicinesRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/prescription': typeof AuthenticatedPrescriptionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/symptoms': typeof AuthenticatedSymptomsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/admin/encyclopedia': typeof AdminEncyclopediaRoute
  '/encyclopedia/search': typeof EncyclopediaSearchRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/compare': typeof ProductsCompareRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/encyclopedia/disease': typeof AuthenticatedEncyclopediaDiseaseRoute
  '/encyclopedia/food': typeof AuthenticatedEncyclopediaFoodRoute
  '/encyclopedia/medicine': typeof AuthenticatedEncyclopediaMedicineRoute
  '/exercise/$workoutId': typeof AuthenticatedExerciseWorkoutIdRoute
  '/food-log/settings': typeof AuthenticatedFoodLogSettingsRoute
  '/encyclopedia/$category/$slug': typeof EncyclopediaCategorySlugRoute
  '/chat/': typeof AuthenticatedChatIndexRoute
  '/encyclopedia/$category/': typeof EncyclopediaCategoryIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/food': typeof FoodRoute
  '/onboarding': typeof OnboardingRoute
  '/accessibility': typeof AuthenticatedAccessibilityRoute
  '/ai-coach': typeof AuthenticatedAiCoachRoute
  '/analytics': typeof AuthenticatedAnalyticsRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/exercise': typeof AuthenticatedExerciseRouteWithChildren
  '/exercises': typeof AuthenticatedExercisesRoute
  '/food-log': typeof AuthenticatedFoodLogRouteWithChildren
  '/food-scan': typeof AuthenticatedFoodScanRoute
  '/hub': typeof AuthenticatedHubRoute
  '/medicines': typeof AuthenticatedMedicinesRoute
  '/nearby': typeof AuthenticatedNearbyRoute
  '/nutrition': typeof AuthenticatedNutritionRoute
  '/prescription': typeof AuthenticatedPrescriptionRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/reports': typeof AuthenticatedReportsRoute
  '/symptoms': typeof AuthenticatedSymptomsRoute
  '/timeline': typeof AuthenticatedTimelineRoute
  '/vitals': typeof AuthenticatedVitalsRoute
  '/workouts': typeof AuthenticatedWorkoutsRoute
  '/admin/encyclopedia': typeof AdminEncyclopediaRoute
  '/encyclopedia/search': typeof EncyclopediaSearchRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/compare': typeof ProductsCompareRoute
  '/encyclopedia': typeof EncyclopediaIndexRoute
  '/products': typeof ProductsIndexRoute
  '/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/encyclopedia/disease': typeof AuthenticatedEncyclopediaDiseaseRoute
  '/encyclopedia/food': typeof AuthenticatedEncyclopediaFoodRoute
  '/encyclopedia/medicine': typeof AuthenticatedEncyclopediaMedicineRoute
  '/exercise/$workoutId': typeof AuthenticatedExerciseWorkoutIdRoute
  '/food-log/settings': typeof AuthenticatedFoodLogSettingsRoute
  '/encyclopedia/$category/$slug': typeof EncyclopediaCategorySlugRoute
  '/chat': typeof AuthenticatedChatIndexRoute
  '/encyclopedia/$category': typeof EncyclopediaCategoryIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/admin': typeof AdminRouteRouteWithChildren
  '/encyclopedia': typeof EncyclopediaRouteRouteWithChildren
  '/products': typeof ProductsRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/food': typeof FoodRoute
  '/onboarding': typeof OnboardingRoute
  '/_authenticated/accessibility': typeof AuthenticatedAccessibilityRoute
  '/_authenticated/ai-coach': typeof AuthenticatedAiCoachRoute
  '/_authenticated/analytics': typeof AuthenticatedAnalyticsRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/exercise': typeof AuthenticatedExerciseRouteWithChildren
  '/_authenticated/exercises': typeof AuthenticatedExercisesRoute
  '/_authenticated/food-log': typeof AuthenticatedFoodLogRouteWithChildren
  '/_authenticated/food-scan': typeof AuthenticatedFoodScanRoute
  '/_authenticated/hub': typeof AuthenticatedHubRoute
  '/_authenticated/medicines': typeof AuthenticatedMedicinesRoute
  '/_authenticated/nearby': typeof AuthenticatedNearbyRoute
  '/_authenticated/nutrition': typeof AuthenticatedNutritionRoute
  '/_authenticated/prescription': typeof AuthenticatedPrescriptionRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/reports': typeof AuthenticatedReportsRoute
  '/_authenticated/symptoms': typeof AuthenticatedSymptomsRoute
  '/_authenticated/timeline': typeof AuthenticatedTimelineRoute
  '/_authenticated/vitals': typeof AuthenticatedVitalsRoute
  '/_authenticated/workouts': typeof AuthenticatedWorkoutsRoute
  '/admin/encyclopedia': typeof AdminEncyclopediaRoute
  '/encyclopedia/search': typeof EncyclopediaSearchRoute
  '/products/$slug': typeof ProductsSlugRoute
  '/products/compare': typeof ProductsCompareRoute
  '/encyclopedia/': typeof EncyclopediaIndexRoute
  '/products/': typeof ProductsIndexRoute
  '/_authenticated/chat/$threadId': typeof AuthenticatedChatThreadIdRoute
  '/_authenticated/encyclopedia/disease': typeof AuthenticatedEncyclopediaDiseaseRoute
  '/_authenticated/encyclopedia/food': typeof AuthenticatedEncyclopediaFoodRoute
  '/_authenticated/encyclopedia/medicine': typeof AuthenticatedEncyclopediaMedicineRoute
  '/_authenticated/exercise/$workoutId': typeof AuthenticatedExerciseWorkoutIdRoute
  '/_authenticated/food-log/settings': typeof AuthenticatedFoodLogSettingsRoute
  '/encyclopedia/$category/$slug': typeof EncyclopediaCategorySlugRoute
  '/_authenticated/chat/': typeof AuthenticatedChatIndexRoute
  '/encyclopedia/$category/': typeof EncyclopediaCategoryIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/encyclopedia'
    | '/products'
    | '/auth'
    | '/food'
    | '/onboarding'
    | '/accessibility'
    | '/ai-coach'
    | '/analytics'
    | '/dashboard'
    | '/exercise'
    | '/exercises'
    | '/food-log'
    | '/food-scan'
    | '/hub'
    | '/medicines'
    | '/nearby'
    | '/nutrition'
    | '/prescription'
    | '/profile'
    | '/reports'
    | '/symptoms'
    | '/timeline'
    | '/vitals'
    | '/workouts'
    | '/admin/encyclopedia'
    | '/encyclopedia/search'
    | '/products/$slug'
    | '/products/compare'
    | '/encyclopedia/'
    | '/products/'
    | '/chat/$threadId'
    | '/encyclopedia/disease'
    | '/encyclopedia/food'
    | '/encyclopedia/medicine'
    | '/exercise/$workoutId'
    | '/food-log/settings'
    | '/encyclopedia/$category/$slug'
    | '/chat/'
    | '/encyclopedia/$category/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/auth'
    | '/food'
    | '/onboarding'
    | '/accessibility'
    | '/ai-coach'
    | '/analytics'
    | '/dashboard'
    | '/exercise'
    | '/exercises'
    | '/food-log'
    | '/food-scan'
    | '/hub'
    | '/medicines'
    | '/nearby'
    | '/nutrition'
    | '/prescription'
    | '/profile'
    | '/reports'
    | '/symptoms'
    | '/timeline'
    | '/vitals'
    | '/workouts'
    | '/admin/encyclopedia'
    | '/encyclopedia/search'
    | '/products/$slug'
    | '/products/compare'
    | '/encyclopedia'
    | '/products'
    | '/chat/$threadId'
    | '/encyclopedia/disease'
    | '/encyclopedia/food'
    | '/encyclopedia/medicine'
    | '/exercise/$workoutId'
    | '/food-log/settings'
    | '/encyclopedia/$category/$slug'
    | '/chat'
    | '/encyclopedia/$category'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/admin'
    | '/encyclopedia'
    | '/products'
    | '/auth'
    | '/food'
    | '/onboarding'
    | '/_authenticated/accessibility'
    | '/_authenticated/ai-coach'
    | '/_authenticated/analytics'
    | '/_authenticated/dashboard'
    | '/_authenticated/exercise'
    | '/_authenticated/exercises'
    | '/_authenticated/food-log'
    | '/_authenticated/food-scan'
    | '/_authenticated/hub'
    | '/_authenticated/medicines'
    | '/_authenticated/nearby'
    | '/_authenticated/nutrition'
    | '/_authenticated/prescription'
    | '/_authenticated/profile'
    | '/_authenticated/reports'
    | '/_authenticated/symptoms'
    | '/_authenticated/timeline'
    | '/_authenticated/vitals'
    | '/_authenticated/workouts'
    | '/admin/encyclopedia'
    | '/encyclopedia/search'
    | '/products/$slug'
    | '/products/compare'
    | '/encyclopedia/'
    | '/products/'
    | '/_authenticated/chat/$threadId'
    | '/_authenticated/encyclopedia/disease'
    | '/_authenticated/encyclopedia/food'
    | '/_authenticated/encyclopedia/medicine'
    | '/_authenticated/exercise/$workoutId'
    | '/_authenticated/food-log/settings'
    | '/encyclopedia/$category/$slug'
    | '/_authenticated/chat/'
    | '/encyclopedia/$category/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  EncyclopediaRouteRoute: typeof EncyclopediaRouteRouteWithChildren
  ProductsRouteRoute: typeof ProductsRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  FoodRoute: typeof FoodRoute
  OnboardingRoute: typeof OnboardingRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/encyclopedia': {
      id: '/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/encyclopedia'
      preLoaderRoute: typeof EncyclopediaRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/food': {
      id: '/food'
      path: '/food'
      fullPath: '/food'
      preLoaderRoute: typeof FoodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products': {
      id: '/products'
      path: '/products'
      fullPath: '/products'
      preLoaderRoute: typeof ProductsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/accessibility': {
      id: '/_authenticated/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AuthenticatedAccessibilityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/ai-coach': {
      id: '/_authenticated/ai-coach'
      path: '/ai-coach'
      fullPath: '/ai-coach'
      preLoaderRoute: typeof AuthenticatedAiCoachRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/analytics': {
      id: '/_authenticated/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AuthenticatedAnalyticsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercise': {
      id: '/_authenticated/exercise'
      path: '/exercise'
      fullPath: '/exercise'
      preLoaderRoute: typeof AuthenticatedExerciseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercises': {
      id: '/_authenticated/exercises'
      path: '/exercises'
      fullPath: '/exercises'
      preLoaderRoute: typeof AuthenticatedExercisesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food-log': {
      id: '/_authenticated/food-log'
      path: '/food-log'
      fullPath: '/food-log'
      preLoaderRoute: typeof AuthenticatedFoodLogRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/food-scan': {
      id: '/_authenticated/food-scan'
      path: '/food-scan'
      fullPath: '/food-scan'
      preLoaderRoute: typeof AuthenticatedFoodScanRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/hub': {
      id: '/_authenticated/hub'
      path: '/hub'
      fullPath: '/hub'
      preLoaderRoute: typeof AuthenticatedHubRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/medicines': {
      id: '/_authenticated/medicines'
      path: '/medicines'
      fullPath: '/medicines'
      preLoaderRoute: typeof AuthenticatedMedicinesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nearby': {
      id: '/_authenticated/nearby'
      path: '/nearby'
      fullPath: '/nearby'
      preLoaderRoute: typeof AuthenticatedNearbyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/nutrition': {
      id: '/_authenticated/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof AuthenticatedNutritionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/prescription': {
      id: '/_authenticated/prescription'
      path: '/prescription'
      fullPath: '/prescription'
      preLoaderRoute: typeof AuthenticatedPrescriptionRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/reports': {
      id: '/_authenticated/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AuthenticatedReportsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/symptoms': {
      id: '/_authenticated/symptoms'
      path: '/symptoms'
      fullPath: '/symptoms'
      preLoaderRoute: typeof AuthenticatedSymptomsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/timeline': {
      id: '/_authenticated/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AuthenticatedTimelineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/vitals': {
      id: '/_authenticated/vitals'
      path: '/vitals'
      fullPath: '/vitals'
      preLoaderRoute: typeof AuthenticatedVitalsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/workouts': {
      id: '/_authenticated/workouts'
      path: '/workouts'
      fullPath: '/workouts'
      preLoaderRoute: typeof AuthenticatedWorkoutsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/admin/encyclopedia': {
      id: '/admin/encyclopedia'
      path: '/encyclopedia'
      fullPath: '/admin/encyclopedia'
      preLoaderRoute: typeof AdminEncyclopediaRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/encyclopedia/': {
      id: '/encyclopedia/'
      path: '/'
      fullPath: '/encyclopedia/'
      preLoaderRoute: typeof EncyclopediaIndexRouteImport
      parentRoute: typeof EncyclopediaRouteRoute
    }
    '/encyclopedia/search': {
      id: '/encyclopedia/search'
      path: '/search'
      fullPath: '/encyclopedia/search'
      preLoaderRoute: typeof EncyclopediaSearchRouteImport
      parentRoute: typeof EncyclopediaRouteRoute
    }
    '/products/': {
      id: '/products/'
      path: '/'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/$slug': {
      id: '/products/$slug'
      path: '/$slug'
      fullPath: '/products/$slug'
      preLoaderRoute: typeof ProductsSlugRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/products/compare': {
      id: '/products/compare'
      path: '/compare'
      fullPath: '/products/compare'
      preLoaderRoute: typeof ProductsCompareRouteImport
      parentRoute: typeof ProductsRouteRoute
    }
    '/_authenticated/chat/': {
      id: '/_authenticated/chat/'
      path: '/chat'
      fullPath: '/chat/'
      preLoaderRoute: typeof AuthenticatedChatIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/chat/$threadId': {
      id: '/_authenticated/chat/$threadId'
      path: '/chat/$threadId'
      fullPath: '/chat/$threadId'
      preLoaderRoute: typeof AuthenticatedChatThreadIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encyclopedia/disease': {
      id: '/_authenticated/encyclopedia/disease'
      path: '/encyclopedia/disease'
      fullPath: '/encyclopedia/disease'
      preLoaderRoute: typeof AuthenticatedEncyclopediaDiseaseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encyclopedia/food': {
      id: '/_authenticated/encyclopedia/food'
      path: '/encyclopedia/food'
      fullPath: '/encyclopedia/food'
      preLoaderRoute: typeof AuthenticatedEncyclopediaFoodRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/encyclopedia/medicine': {
      id: '/_authenticated/encyclopedia/medicine'
      path: '/encyclopedia/medicine'
      fullPath: '/encyclopedia/medicine'
      preLoaderRoute: typeof AuthenticatedEncyclopediaMedicineRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/exercise/$workoutId': {
      id: '/_authenticated/exercise/$workoutId'
      path: '/$workoutId'
      fullPath: '/exercise/$workoutId'
      preLoaderRoute: typeof AuthenticatedExerciseWorkoutIdRouteImport
      parentRoute: typeof AuthenticatedExerciseRoute
    }
    '/_authenticated/food-log/settings': {
      id: '/_authenticated/food-log/settings'
      path: '/settings'
      fullPath: '/food-log/settings'
      preLoaderRoute: typeof AuthenticatedFoodLogSettingsRouteImport
      parentRoute: typeof AuthenticatedFoodLogRoute
    }
    '/encyclopedia/$category/': {
      id: '/encyclopedia/$category/'
      path: '/$category'
      fullPath: '/encyclopedia/$category/'
      preLoaderRoute: typeof EncyclopediaCategoryIndexRouteImport
      parentRoute: typeof EncyclopediaRouteRoute
    }
    '/encyclopedia/$category/$slug': {
      id: '/encyclopedia/$category/$slug'
      path: '/$category/$slug'
      fullPath: '/encyclopedia/$category/$slug'
      preLoaderRoute: typeof EncyclopediaCategorySlugRouteImport
      parentRoute: typeof EncyclopediaRouteRoute
    }
  }
}

interface AuthenticatedExerciseRouteChildren {
  AuthenticatedExerciseWorkoutIdRoute: typeof AuthenticatedExerciseWorkoutIdRoute
}

const AuthenticatedExerciseRouteChildren: AuthenticatedExerciseRouteChildren = {
  AuthenticatedExerciseWorkoutIdRoute: AuthenticatedExerciseWorkoutIdRoute,
}

const AuthenticatedExerciseRouteWithChildren =
  AuthenticatedExerciseRoute._addFileChildren(
    AuthenticatedExerciseRouteChildren,
  )

interface AuthenticatedFoodLogRouteChildren {
  AuthenticatedFoodLogSettingsRoute: typeof AuthenticatedFoodLogSettingsRoute
}

const AuthenticatedFoodLogRouteChildren: AuthenticatedFoodLogRouteChildren = {
  AuthenticatedFoodLogSettingsRoute: AuthenticatedFoodLogSettingsRoute,
}

const AuthenticatedFoodLogRouteWithChildren =
  AuthenticatedFoodLogRoute._addFileChildren(AuthenticatedFoodLogRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAccessibilityRoute: typeof AuthenticatedAccessibilityRoute
  AuthenticatedAiCoachRoute: typeof AuthenticatedAiCoachRoute
  AuthenticatedAnalyticsRoute: typeof AuthenticatedAnalyticsRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExerciseRoute: typeof AuthenticatedExerciseRouteWithChildren
  AuthenticatedExercisesRoute: typeof AuthenticatedExercisesRoute
  AuthenticatedFoodLogRoute: typeof AuthenticatedFoodLogRouteWithChildren
  AuthenticatedFoodScanRoute: typeof AuthenticatedFoodScanRoute
  AuthenticatedHubRoute: typeof AuthenticatedHubRoute
  AuthenticatedMedicinesRoute: typeof AuthenticatedMedicinesRoute
  AuthenticatedNearbyRoute: typeof AuthenticatedNearbyRoute
  AuthenticatedNutritionRoute: typeof AuthenticatedNutritionRoute
  AuthenticatedPrescriptionRoute: typeof AuthenticatedPrescriptionRoute
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedReportsRoute: typeof AuthenticatedReportsRoute
  AuthenticatedSymptomsRoute: typeof AuthenticatedSymptomsRoute
  AuthenticatedTimelineRoute: typeof AuthenticatedTimelineRoute
  AuthenticatedVitalsRoute: typeof AuthenticatedVitalsRoute
  AuthenticatedWorkoutsRoute: typeof AuthenticatedWorkoutsRoute
  AuthenticatedChatThreadIdRoute: typeof AuthenticatedChatThreadIdRoute
  AuthenticatedEncyclopediaDiseaseRoute: typeof AuthenticatedEncyclopediaDiseaseRoute
  AuthenticatedEncyclopediaFoodRoute: typeof AuthenticatedEncyclopediaFoodRoute
  AuthenticatedEncyclopediaMedicineRoute: typeof AuthenticatedEncyclopediaMedicineRoute
  AuthenticatedChatIndexRoute: typeof AuthenticatedChatIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAccessibilityRoute: AuthenticatedAccessibilityRoute,
  AuthenticatedAiCoachRoute: AuthenticatedAiCoachRoute,
  AuthenticatedAnalyticsRoute: AuthenticatedAnalyticsRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExerciseRoute: AuthenticatedExerciseRouteWithChildren,
  AuthenticatedExercisesRoute: AuthenticatedExercisesRoute,
  AuthenticatedFoodLogRoute: AuthenticatedFoodLogRouteWithChildren,
  AuthenticatedFoodScanRoute: AuthenticatedFoodScanRoute,
  AuthenticatedHubRoute: AuthenticatedHubRoute,
  AuthenticatedMedicinesRoute: AuthenticatedMedicinesRoute,
  AuthenticatedNearbyRoute: AuthenticatedNearbyRoute,
  AuthenticatedNutritionRoute: AuthenticatedNutritionRoute,
  AuthenticatedPrescriptionRoute: AuthenticatedPrescriptionRoute,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedReportsRoute: AuthenticatedReportsRoute,
  AuthenticatedSymptomsRoute: AuthenticatedSymptomsRoute,
  AuthenticatedTimelineRoute: AuthenticatedTimelineRoute,
  AuthenticatedVitalsRoute: AuthenticatedVitalsRoute,
  AuthenticatedWorkoutsRoute: AuthenticatedWorkoutsRoute,
  AuthenticatedChatThreadIdRoute: AuthenticatedChatThreadIdRoute,
  AuthenticatedEncyclopediaDiseaseRoute: AuthenticatedEncyclopediaDiseaseRoute,
  AuthenticatedEncyclopediaFoodRoute: AuthenticatedEncyclopediaFoodRoute,
  AuthenticatedEncyclopediaMedicineRoute:
    AuthenticatedEncyclopediaMedicineRoute,
  AuthenticatedChatIndexRoute: AuthenticatedChatIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminEncyclopediaRoute: typeof AdminEncyclopediaRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminEncyclopediaRoute: AdminEncyclopediaRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface EncyclopediaRouteRouteChildren {
  EncyclopediaSearchRoute: typeof EncyclopediaSearchRoute
  EncyclopediaIndexRoute: typeof EncyclopediaIndexRoute
  EncyclopediaCategorySlugRoute: typeof EncyclopediaCategorySlugRoute
  EncyclopediaCategoryIndexRoute: typeof EncyclopediaCategoryIndexRoute
}

const EncyclopediaRouteRouteChildren: EncyclopediaRouteRouteChildren = {
  EncyclopediaSearchRoute: EncyclopediaSearchRoute,
  EncyclopediaIndexRoute: EncyclopediaIndexRoute,
  EncyclopediaCategorySlugRoute: EncyclopediaCategorySlugRoute,
  EncyclopediaCategoryIndexRoute: EncyclopediaCategoryIndexRoute,
}

const EncyclopediaRouteRouteWithChildren =
  EncyclopediaRouteRoute._addFileChildren(EncyclopediaRouteRouteChildren)

interface ProductsRouteRouteChildren {
  ProductsSlugRoute: typeof ProductsSlugRoute
  ProductsCompareRoute: typeof ProductsCompareRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
}

const ProductsRouteRouteChildren: ProductsRouteRouteChildren = {
  ProductsSlugRoute: ProductsSlugRoute,
  ProductsCompareRoute: ProductsCompareRoute,
  ProductsIndexRoute: ProductsIndexRoute,
}

const ProductsRouteRouteWithChildren = ProductsRouteRoute._addFileChildren(
  ProductsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  EncyclopediaRouteRoute: EncyclopediaRouteRouteWithChildren,
  ProductsRouteRoute: ProductsRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  FoodRoute: FoodRoute,
  OnboardingRoute: OnboardingRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
